# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"


  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      #- name: Delete branch
       # uses: dawidd6/action-delete-branch@v3
        #with:
         # github_token: ${{ secrets.GITHUB_TOKEN }}
          #branches: action-test
     # - name: Create Branch
      #  uses: peterjgrainger/action-create-branch@v2.0.1
       # env:
       #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       # with:
         # branch: 'action-test'    
      - name: Push to built branch
        uses: remo285/action-commit-to-branch@master
        with:
          branch: 'action-test'
          commit_message: 'update build'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
